.data
	# bitmap cache
	.eqv START_GAME_CACHE		0
	.eqv FIRST_PHASE_CACHE		1
	.eqv SECOND_PHASE_CACHE		2
	.eqv THIRD_PHASE_CACHE		3
	.eqv FOURTH_PHASE_CACHE		4
	.eqv FIFTH_PHASE_CACHE		5
	.eqv SIXTH_PHASE_CACHE		6
	.eqv SEVENTH_PHASE_CACHE	7
	.eqv EIGHTH_PHASE_CACHE		8
	.eqv NINTH_PHASE_CACHE		9
	.eqv TENTH_PHASE_CACHE		10